### ISSUE TITLE
Homepage: The yellow background on "Welcome - Ripe Inflatable Packers" is missing

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#10]
PSD design shows a yellow background/container on this area.

**Comment by rexcebudigital** [comment]
Can I request a screenshot for this issue? Thanks.

**Comment by ermatitan** [comment]
screenshot attached...
![image](https://cloud.githubusercontent.com/assets/12791909/8472368/3b6077b2-20d3-11e5-8fc1-979ca3c074ba.png)

**Comment by arielcebudigital** [comment]
You can use either one of the design layout.. The white background or the yellow one..:-)

**Comment by rexcebudigital** [comment]
Hi Erma, I clarified this one to our Team Lead, He said that we can choose what design on the PSD either the layout with a yellow background or the other one which is the black background. 

So I will label this one Invalid because I don't see any issue on this. Thank Erma.

**Comment by christiancebudigital** [comment]
Hi Erma,

I've noted in the project scope to use HOME PAGE 1B, under PAGE/ SECTION/ETC, this is not a bug, would it be ok to updated this ticket :)..

Thanks,
Christian
