### ISSUE TITLE
Overlapping of product specification label if more than one line long

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#128]
Devices: S4 and iTOuch

![image](https://cloud.githubusercontent.com/assets/12791909/9076702/6ae326d4-3b58-11e5-9691-9629f40916f7.png)

**Comment by ermatitan** [comment]
Not fix, overlapping occurs when label is selected.

![image](https://cloud.githubusercontent.com/assets/12791909/9101091/f45c0d6a-3c14-11e5-947b-fd4b9e275a27.png)

**Comment by ermatitan** [comment]
not fix

**Comment by rexcebudigital** [comment]
Hi Erma, I don't see this issue on my end. Can you please try to press ctrl+f5.
If this issue is still not solve, please paste the testing URL here. Thanks.

**Comment by ermatitan** [comment]
http://ripepackers.stage.titanweb.com.au/products/category-test-3/wednesday-product-test/#id_6



![image](https://cloud.githubusercontent.com/assets/12791909/9158198/c90e6f76-3f44-11e5-9bcb-20dd808dc775.png)
