### ISSUE TITLE
Upper line separator for product specification label disappears when selected.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#131]
Ipad Air, S4 and iTouch 

![image](https://cloud.githubusercontent.com/assets/12791909/9101120/4682315a-3c15-11e5-838b-700e1f21d1ad.png)

**Comment by ermatitan** [comment]
not fix

**Comment by rexcebudigital** [comment]
Hi Erma, I don't see this issue on my end. Can you please try to press ctrl+f5.
If this issue is still not solve, please paste the testing URL here. Thanks.

**Comment by ermatitan** [comment]
http://ripepackers.stage.titanweb.com.au/products/category-test-3/wednesday-product-test/#id_4

![image](https://cloud.githubusercontent.com/assets/12791909/9158205/f4840cf6-3f44-11e5-99ef-7f4628a3d446.png)
