### ISSUE TITLE
Product Single Page: Long product specification label also got impact on desktop view on all browsers.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#132]
This is related to #118. If we can limit the number of repeater the user can add, it think it would be better to prevent more error on the front-end.

![image](https://cloud.githubusercontent.com/assets/12791909/9101193/5d6c8e46-3c16-11e5-8f00-7464e193520e.png)

**Comment by ermatitan** [comment]
Not fix

**Comment by rexcebudigital** [comment]
Hi Erma, I don't see this issue on my end. Can you please try to press ctrl+f5.
If this issue is still not solve, please paste the testing URL here. Thanks.

**Comment by ermatitan** [comment]
Please see my updated screenshot. http://ripepackers.stage.titanweb.com.au/products/category-test-3/wednesday-product-test/#id_6

![image](https://cloud.githubusercontent.com/assets/12791909/9158065/e90d7594-3f42-11e5-9e93-9601dcb610a4.png)
