### ISSUE TITLE
Homepage: Broken banner was observed in Chrome

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#134]
![image](https://cloud.githubusercontent.com/assets/12791909/9101660/302dbce2-3c1c-11e5-9e3c-7c5b64c4b640.png)

**Comment by ermatitan** [comment]
Not fix

**Comment by rexcebudigital** [comment]
Hi Erma, I don't see this issue on my end. Try to press ctrl+0 to set the default view of the browser. Please see screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/11186391/9108383/47a11eca-3c60-11e5-8c15-e9081fa931e9.jpg)

**Comment by ermatitan** [comment]
problem fix
