### ISSUE TITLE
General: Page title and content should be aligned center in all mobile devices to be consistent since featured images and sidebar are all centered.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#135]
![image](https://cloud.githubusercontent.com/assets/12791909/9105272/d135603c-3c48-11e5-8368-cabeaaf5dff8.png)

**Comment by ermatitan** [comment]
I have cleared my mobile cache. Problem still reproducible in the following pages:

Recent projects
Our Products
Gallery
News
Services
Downloads
About Us
Sitemap

**Comment by ermatitan** [comment]
Project Title not centered.
http://ripepackers.stage.titanweb.com.au/recent-projects/

**Comment by ermatitan** [comment]
not fix

**Comment by rexcebudigital** [comment]
This is already fixed on my end. I will label this an invalid since it is already fixed. Try CTRL+F5

**Comment by rexcebudigital** [comment]
Center alignment will only be implemented on portrait view. It doesn't look good to center the project title on landscape view.

**Comment by ermatitan** [comment]
A few items not centered on portrait view: S4 ; iTouch

Project Page: Project title not centered
![image](https://cloud.githubusercontent.com/assets/12791909/9265598/353f2174-4268-11e5-999a-afa79b00032f.png)

Services Page: Contact us button not centered
![image](https://cloud.githubusercontent.com/assets/12791909/9265603/434c1e70-4268-11e5-841c-cf367d7f46ec.png)
