### ISSUE TITLE
Recent Projects: Line separator touches with the sidebar on Ipad Air (portrait view)

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#136]
![image](https://cloud.githubusercontent.com/assets/12791909/9159080/558cb994-3f54-11e5-9390-0d915d1bba82.png)

**Comment by ermatitan** [comment]
not fix

**Comment by rexcebudigital** [comment]
Its is already fixed on my end. I will label this as an invalid. Try ctrl+F5
