### ISSUE TITLE
Sidebar categories are clipped on some pages after viewing from landscape to portrait mode

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#140]
Devices: Ipad; Ipad Air

Problem occurs on the following pages:

Project Single Page
Product single Page
About Us Page
Sitemap Page
Privacy Policy Page
Thank You Page
News Single Page

![image](https://cloud.githubusercontent.com/assets/12791909/9244222/dcb85116-41cb-11e5-81a8-c667fc821469.png)

**Comment by rexcebudigital** [comment]
This is not a sidebar categories. This is homepage product categories.

**Comment by ermatitan** [comment]
Sorry i have pasted the wrong screenshot. New screenshot attached

**Comment by ermatitan** [comment]
not fix. please updated screenshot:

![image](https://cloud.githubusercontent.com/assets/12791909/9265336/4eaf24a0-4264-11e5-8e9f-ccb1f76cf028.png)

**Comment by rexcebudigital** [comment]
I don't see the issue on my end.

**Comment by ermatitan** [comment]
I was able to create this on Chrome - Emulator

![image](https://cloud.githubusercontent.com/assets/12791909/9267137/8652294e-427c-11e5-85aa-0fedcefbf66b.png)

**Comment by ermatitan** [comment]
I can still recreate the issue on 
About Us page
Our Product Page
Product single page
Project single page

**Comment by rexcebudigital** [comment]
I have tested the issue on real iPad and I don't see any issues.

By testing the chrome developers tool maybe we should reload the page for proper rendering.
I don't get the point why issued a bug since it is not actually a bug on iPad device. Please see screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/11186391/9269160/1b86d2d2-4299-11e5-8b07-ae00d9b572cd.jpg)

**Comment by ermatitan** [comment]
I have also tested this on the actual device and was able to recreate the issue at once. 

![image](https://cloud.githubusercontent.com/assets/12791909/9269306/d5af23ca-429a-11e5-9fea-05fe12b4eb65.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

It seems, that we cant replicate your issue, we have our ipad here also, and it seems that it is working well on our end, we are clarifying this issue to Bernard right now, hope this gets resolve :D.

Thanks,
Christian
