### ISSUE TITLE
Request a Quote: Font color and format still is the same with the form field label

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#18]
![image](https://cloud.githubusercontent.com/assets/12791909/8449898/03574556-2008-11e5-975f-b5c486c5be83.png)

**Comment by rexcebudigital** [comment]
Hi Erma, I already implemented the enhancement for this. Please see screenshot below. Thanks.
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8612877/8615f3da-270a-11e5-93ae-a353e44237e3.png)
