### ISSUE TITLE
Inner Banner width is not the same with PSD Design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#26]
The Inner banner left width should overlap with the logo as specified in the PSD Design

![image](https://cloud.githubusercontent.com/assets/12791909/8472589/1905896c-20d5-11e5-89e5-d7624bbd2af6.png)

**Comment by arielcebudigital** [comment]
I think that the logo is not consistent it should be the same to the sub-pages.

**Comment by ermatitan** [comment]
not fix on firefox

![image](https://cloud.githubusercontent.com/assets/12791909/8689280/0cecd632-2ad8-11e5-9d02-ea6647086351.png)

**Comment by ermatitan** [comment]
Problem still not fix. Minimizing the browser is just a little bit will result to images not equal in size.
