### ISSUE TITLE
Product gallery images not formatted properly

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#28]
![image](https://cloud.githubusercontent.com/assets/12791909/8473236/64442fd2-20da-11e5-888b-100d2f1f74b6.png)

**Comment by arielcebudigital** [comment]
Please don't remove the test page, or just put the link so that we can find it easily. :-)

**Comment by arielcebudigital** [comment]
Please don't try to add anything that has not in PSD or in the project scope.

**Comment by ermatitan** [comment]
Not fix

![image](https://cloud.githubusercontent.com/assets/12791909/8669489/c63d3230-2a47-11e5-9142-ea14deaedfca.png)
