### ISSUE TITLE
Homepage: Find out more button has no active state

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#37]
Find out more button should change its color when mouse manuever or when click

![image](https://cloud.githubusercontent.com/assets/12791909/8494428/8421b244-2197-11e5-871d-eaa0ddc23798.png)

**Comment by arielcebudigital** [comment]
Please check the PSD, the button has no active state.

**Comment by rexcebudigital** [comment]
Hi Erma,

First when we hover this button it was: 
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8611159/46bc62b6-26ef-11e5-948e-1500722bd6ca.png)


I did not see any hover effect on the PSD file.
It doesn't look good to have an underline when hover, so I will take out the underline and leave it at it is. 

Do you have any suggestion to this?

I will take out Ariel's invalid label and change it to enchancement. Thanks.

**Comment by christiancebudigital** [comment]
Hi Erma,

Base on the PSD file on homepage, there is an active state see attached screenshot1 [inactive.jpg
![inactive](https://cloud.githubusercontent.com/assets/11186331/8716567/29728854-2bc5-11e5-9141-aedf80b17e61.jpg)
]
see active state
![active](https://cloud.githubusercontent.com/assets/11186331/8716568/30730bc4-2bc5-11e5-9207-ee2ad7f65880.jpg)

cursor pointer on "Find out more" is just OK when hovered on the button which is already been implemented, please update the label on this issue thanks.

Cheers,
Christian
