### ISSUE TITLE
Read Less functionality intermittently disappears from the homepage

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#43]
Devices: Ipad Air , Samsung Tab 3

> On the homepage, click on the Read More link
> Homepage full content displays
> Click on the  Logo and notice that the Read Less text at the bottom of the homepage is gone.

![image](https://cloud.githubusercontent.com/assets/12791909/8514573/dfb2a864-23c4-11e5-920a-5b8533d95c65.png)

**Comment by ermatitan** [comment]
I can still recreate this issue on mobile devices: Ipad Air, Samsung Tab

**Comment by ermatitan** [comment]
problem re-occur on ipad air

**Comment by rexcebudigital** [comment]
As I've checked on my end I don't see any issues. Can you provide a screenshot for the issue.

**Comment by ermatitan** [comment]
screenshot taken from Samsung S4

![image](https://cloud.githubusercontent.com/assets/12791909/9192757/5e3bb2f6-4040-11e5-8482-ca0c18ddfdf1.png)

**Comment by rexcebudigital** [comment]
Please wait for Christians comments for this issue. Thanks.

**Comment by christiancebudigital** [comment]
Hi Erma,

we have tested this bug on our end, and it seems that we cant replicated it because we dont have the actual device, anyways, well send this one for pre live.

Thanks,
Christian
