### ISSUE TITLE
Service custom post sidebar not found on some pages

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#44]
Project Scope specify that Project, Products, Product listing, Downloads, About us should have a service custom post on the sider. 

Custom post sidebar not does specify on the PSD Design

![image](https://cloud.githubusercontent.com/assets/12791909/8514856/751f1ee6-23ca-11e5-8691-cba2e98229a2.png)

**Comment by christiancebudigital** [comment]
Hi Erma,

Thanks for this note, we have now updated the project scope, ive deleted this text "service custom post on sidebar**** " there was a note at the bottom of the project scope [ do not implement **** ], hope this anwer your question.

Cheers,
Christian
