### ISSUE TITLE
Gallery images are stretch on gallery pages on portrait view.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#52]
Device: Samsung Tab 3 Lite

![image](https://cloud.githubusercontent.com/assets/12791909/8516306/33c0b886-23e5-11e5-92f0-dd18f8f9e3a5.png)

**Comment by rexcebudigital** [comment]
Hi Erma, I have updated the css and tested it and it works, can you please check it again on your end.
And can you please use or upload new images when trying to add a gallery. It is better when you upload a new images because it will generate or crop the uploaded images.

Thanks.
