### ISSUE TITLE
Gallery height not the same

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#53]
Device : Samsung Tab 3

http://ripepackers.stage.titanweb.com.au/gallery-album/

![image](https://cloud.githubusercontent.com/assets/12791909/8516392/3cabd8bc-23e6-11e5-950d-898945db0c3d.png)

**Comment by rexcebudigital** [comment]
Hi Erma, I have tested it on my end on browsers and iPad and Samsung devices and I don't see an issue. I can say that the issue exist when you use an existing image on the Media Library. Can you try making a gallery and insert it on the album and please upload new images to it. 

Please do let me know if the issue still exist.
Here's my screenshot:
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8613881/71bf0a3c-2716-11e5-9026-9a6574724a05.png)


Thanks.
