### ISSUE TITLE
Projects and Services pagination

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#55]
Based on project scope, recent project pagination start after 3 while on services, pagination starts after 5.

On the actual site, project pagination starts after 3 and for services page, pagination starts after 4.

PSD Design shows only 4 items on the services page. Should services page follow the psd design for pagination? Or the project scope?

**Comment by rexcebudigital** [comment]
Hi Erma,

The project scope is now updated. Kindly check on this section. Thanks. 

Here's the link of the project scope: https://docs.google.com/spreadsheets/d/17Asl215UykWcxlor3SeSVIAjfbR6XeAACY7MWAtUt9k/edit?pli=1#gid=2035631399
