### ISSUE TITLE
Banner navigation buttons and title not displayed

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#59]
Devices: 
Samsung Tab 3 (portrait mode)
Samsung S4 (landscape and portrait mode)
Itouch (landscape and portrait mode)

![image](https://cloud.githubusercontent.com/assets/12791909/8517991/8e47e910-23f8-11e5-99c9-d36f9c330663.png)

**Comment by rexcebudigital** [comment]
Hi Erma,

I don't see this issue on my end. Kindly try to clear your cache thanks.
