### ISSUE TITLE
Our Products page - no pagination implemented. 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#60]
As per project scope, "paginate if more than 6 - basic pagination"

**Comment by rexcebudigital** [comment]
Hi Erma,

I haven't updated anything. This was already implemented. Thanks. 
Please allow me to change the label into invalid.

See screenshot below:
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8693318/dd1e242a-2b08-11e5-9cea-3b22d3113fdb.png)

**Comment by rexcebudigital** [comment]
Hi Erma,

As per Bernard. The pagination will only effect on the product listing page, and not in the category listing page.
