### ISSUE TITLE
Services single page - featured image size not the same with about us psd design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#75]
![image](https://cloud.githubusercontent.com/assets/12791909/8691146/c8f2d9e4-2af1-11e5-9656-d690d562555b.png)

**Comment by rexcebudigital** [comment]
Hi Erma,

Single page is now the same with the psd file of about us page. If you add a new featured image for a particular post. Please upload a new image. Thanks.

Here's my screenshot: Note: featured image width is 328px and height is 328px
![welcome ripe inflatable packers ripe packers](https://cloud.githubusercontent.com/assets/11186391/8696133/6c460380-2b1c-11e5-90b5-199a0ef1dc75.png)
