### ISSUE TITLE
Clarrification: Where should services custom post sidebar be displayed?

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#82]
Based on project scope; services custom post sidebar will be displayed on the following pages: 
NEWS SINGLE PAGE, NEWS PAGE, RECENT PROJECTS, DOWNLOADS, SERVICES PAGE, OUR PRODUCTS LISTING PAGE, OUR PRODUCTS PAGE

While on PSD Design, services custom post sidebar was only displayed on Services page.

**Comment by christiancebudigital** [comment]
Hi Erma,

Thanks for this note, we have now updated the project scope, ive deleted this text "service custom post on sidebar**** " there was a note at the bottom of the project scope [ do not implement **** ], hope this anwer your question.

Cheers,
Christian
