### ISSUE TITLE
Banner navigation buttons are clipped.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#90]
Devices: Samsung S4

![image](https://cloud.githubusercontent.com/assets/12791909/8793613/1d0cca9e-2fac-11e5-9850-60e4154898b5.png)

**Comment by ermatitan** [comment]
Not fix. Problem still reproducible

**Comment by ermatitan** [comment]
Not fix. Already cleared my cache and problem still reproducible

**Comment by rexcebudigital** [comment]
Hi Erma, I will address this issue to Christian since I cannot replicate this issue on my end. Thanks. I will just change the label and talk with Christian tomorrow about the issue.

**Comment by christiancebudigital** [comment]
Hi Erma,

This issue is ok on our emulator, but since we cant replicate it in our end in an actual device, well label this one as fixed, and will send this off to pre live fixes, I've talked to Bernard regarding this issue, and we both agree to send this as prelive fixes.

Cheers,
Christian
