### ISSUE TITLE
Ipad Air: Image background not equal in width

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#94]
Portrait View:
![image](https://cloud.githubusercontent.com/assets/12791909/8793843/dca171a0-2fae-11e5-8f36-a7de2d5e6107.png)

Landscape View:
![image](https://cloud.githubusercontent.com/assets/12791909/8793861/f9d900e4-2fae-11e5-9e59-62d6f4fbabd7.png)

**Comment by rexcebudigital** [comment]
Hi Erma, for the portrait view I just align it with the header and for the landscape view, I just followed on what the PSD design looks like. Thanks.

**Comment by ermatitan** [comment]
Hello Rex, portrait view is all good, but for landscape view, the banner should be aligned with Our products and Enquire Now to make it look good
