### ISSUE TITLE
Contact Us: Country field has rounded edge which is inconsistent to the rest of the field.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Replacement-Inflatable-Packers#98]
Device: Samsung Tab 3

![image](https://cloud.githubusercontent.com/assets/12791909/8844735/f9b1ed2c-314a-11e5-8429-485e3a0c7e2e.png)

**Comment by rexcebudigital** [comment]
Hi Erma, we can't replicate the issue here, please be patient. I added some changes for this. Please do let me know if the bug still occur. Thanks.
